Add Keystore

diff --git a/.github/workflows/publish-beta.yml b/.github/workflows/publish-beta.yml
--- a/.github/workflows/publish-beta.yml
+++ b/.github/workflows/publish-beta.yml
@@ -106,10 +106,14 @@ jobs:
         run: echo VERSION_NUMBER=$(node -p -e "require('./package.json').version") >> $GITHUB_ENV
       
       - name: 🔑 Setup release keystore
-        if: secrets.ANDROID_SIGNING_BASE64 != ''
         run: |
-          echo "${{ secrets.ANDROID_SIGNING_BASE64 }}" | base64 --decode > android/app/jellify.keystore
-          echo "Release keystore created"
+          if [ -n "${{ secrets.ANDROID_SIGNING_BASE64 }}" ]; then
+            echo "${{ secrets.ANDROID_SIGNING_BASE64 }}" | base64 --decode > android/app/jellify.keystore
+            echo "Release keystore created"
+          else
+            echo "ERROR: No keystore secret found!"
+            exit 1
+          fi
       
       - name: 🤫 Output TelemetryDeck Secrets to TelemetryDeck.json          
         run: |
